name = "SatelliteSimPlatformControl"
uuid = "55b52c20-d4e9-4de3-9386-a282bcb160fa"
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PlatformRunner = "c8302b0a-46a2-4f81-9ea9-cb0d56cb7a01"
SatelliteSimPlatformKubernetes = "e2f55f19-4ad2-484e-96cc-4a92e0ba23b7"
SatelliteSimPlatformStorage = "b35ff6da-ef20-4246-8527-f3c478659baf"

[sources]
PlatformRunner = {path = "../runner"}
SatelliteSimPlatformKubernetes = {path = "../kubernetes"}
SatelliteSimPlatformStorage = {path = "../storage"}

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
