name = "SatelliteSimPlatformRuntime"
uuid = "f0679bbe-6520-4587-9fd1-0d8698fb7505"
version = "0.1.0"

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PlatformRunner = "c8302b0a-46a2-4f81-9ea9-cb0d56cb7a01"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
SatelliteSimPlatformControl = "55b52c20-d4e9-4de3-9386-a282bcb160fa"
SatelliteSimPlatformKubernetes = "e2f55f19-4ad2-484e-96cc-4a92e0ba23b7"
SatelliteSimPlatformStorage = "b35ff6da-ef20-4246-8527-f3c478659baf"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[sources]
PlatformRunner = {path = "../runner"}
SatelliteSimPlatformControl = {path = "../control"}
SatelliteSimPlatformKubernetes = {path = "../kubernetes"}
SatelliteSimPlatformStorage = {path = "../storage"}

[compat]
DBInterface = "2"
JSON = "0.21"
SQLite = "1.8"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
